using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace KU.Repositories.Models
{
   // public class QuestionnaireWrap9
    //{
    //    public QuestionnaireWrap9()
    //    {
    //        result = new List<Questionnaire9>();

    //    }
    //    public IEnumerable<Questionnaire9> result { get; set; }

    //}
    public class Questionnaire9
    {
        [Key]
       public string savedformID { get; set; }
        public string sample { get; set; }
        public string Depository_ID { get; set; }
        public string projecttitle { get; set; }
        public string principalinvestigator { get; set; }
        public string collection_point { get; set; }
        public string collected_by { get; set; }
        public string collected_date { get; set; }
        public string gender { get; set; }
        public string country { get; set; }
        public string nationality { get; set; }
        public string dob { get; set; }
        public string PlaceOfBirth { get; set; }
        public string city { get; set; }
        public string age { get; set; }
        public string pers_Numberofwives { get; set; }
        public string pers_BoysGirls { get; set; }
        public string pers_Girls { get; set; }
        public string pers_Boys { get; set; }
        public string ethnicity { get; set; }
        public string ethnicity_mixed_specify_text { get; set; }
        public string ethnicity_others_text { get; set; }
        public string maritalstatus { get; set; }
        public string marriage_con { get; set; }
        public string pers_NumberofChildren { get; set; }
        public string highest_grade { get; set; }
        public string highest_degree_earned { get; set; }
        public string eduGradel { get; set; }
        public string eduLevel { get; set; }
        public string household { get; set; }
        public string household_minor { get; set; }
        public string ownresidence { get; set; }
        public string employment_status { get; set; }
        public string employment_work { get; set; }
        public string employment_nightshift { get; set; }
        public string employment_nightshift_others { get; set; }
        public string eduGrade_other { get; set; }
        public string PPA_work_txt { get; set; }
        public string eduLevel_other { get; set; }
        public string employment_nightshift_often { get; set; }
        public string elementary_school { get; set; }
        public string high_school { get; set; }
        public string elementary_school_value { get; set; }
        public string high_school_value { get; set; }
        public string college { get; set; }
        public string college_value { get; set; }
        public string graduate { get; set; }
        public string graduate_value { get; set; }
        public string other_grade { get; set; }
        public string prefernottodisclose_grade { get; set; }
        public string health_overall_4weeks { get; set; }
        public string health_physical_problem_4weeks { get; set; }
        public string health_difficulty_4weeks { get; set; }
        public string health_body_pain_4weeks { get; set; }
        public string health_energy_4weeks { get; set; }
        public string health_emotional_problems_4weeks { get; set; }
        public string health_bothered_emotional_problems_4weeks { get; set; }
        public string health_bothered_emotional_problems_affect_4weeks { get; set; }
        public string health_brushteethtwice_4weeks { get; set; }
        public string health_weight_change { get; set; }
        public string health_special_diet_4weeks { get; set; }
        public string health_bowel_movement_4weeks { get; set; }
        public string health_urinate_4weeks { get; set; }
        public string health_urinate_night_4weeks { get; set; }
        public string health_urinate_night_4weeks_often { get; set; }
        public string health_advcontact { get; set; }
        public string health_emergency { get; set; }
        public string health_emergency_reason { get; set; }
        public string health_hospital { get; set; }
        public string health_hospital_reason { get; set; }
        public string health_advice_noone { get; set; }
        public string health_advice_Dietitian { get; set; }
        public string health_advice_Nurse { get; set; }
        public string health_advice_GP { get; set; }
        public string health_advice_Pharmacist { get; set; }
        public string health_advice_Diabetes_specialist { get; set; }
        public string health_advice_others { get; set; }
        public string health_advice_others_remarks { get; set; }
        public string health_annual_medical_checkup { get; set; }
        public string health_annual_medical_checkuptxtdateyear { get; set; }
        public string female_first_period { get; set; }
        public string female_first_period_others { get; set; }
        public string female_menopause { get; set; }
        public string female_menopause_others { get; set; }
        public string female_period_days { get; set; }
        public string female_period_days_number { get; set; }
        public string female_period_How_often { get; set; }
        public string female_period_How_often_others { get; set; }
        public string female_period_regular_time_intervals { get; set; }
        public string female_period_regular_time_intervals_yes_when { get; set; }
        public string female_period_regular_time_intervals_no_when { get; set; }
        public string female_pregnant { get; set; }
        public string female_pregnant_when { get; set; }
        public string female_pregnant_when_year { get; set; }
        public string female_birth_control { get; set; }
        public string female_birth_control_when { get; set; }
        public string female_birth_control_Which_medication { get; set; }
        public string female_birth_control_dose { get; set; }
        public string female_facial_hair { get; set; }
        public string female_fg_points { get; set; }
        public string health_emergency_my_mental_health { get; set; }
        public string health_emergency_my_physical_health { get; set; }
        public string health_emergency_my_diabetes_status { get; set; }
        public string health_emergency_Non_applicable { get; set; }
        public string health_hospital_my_mental_health { get; set; }
        public string health_hospital_my_physical_health { get; set; }
        public string health_hospital_my_diabetes_status { get; set; }
        public string health_hospital_Non_applicable { get; set; }
        public string PPA_vigorous_physical_activities { get; set; }
        public string PPA_vigorous_physical_activities_days_per_week { get; set; }
        public string PPA_vigorous_physical_activities_time { get; set; }
        public string PPA_vigorous_physical_activities_hours { get; set; }
        public string PPA_vigorous_physical_activities_min { get; set; }
        public string PPA_moderate_physical_activities { get; set; }
        public string PPA_moderate_physical_activities_time { get; set; }
        public string PPA_moderate_physical_activities_hours { get; set; }
        public string PPA_moderate_physical_activities_min { get; set; }
        public string PPA_walk { get; set; }
        public string PPA_walk_days { get; set; }
        public string PPA_walk_time { get; set; }
        public string PPA_walk_time_hours { get; set; }
        public string PPA_walk_time_min { get; set; }
        public string PPA_sit { get; set; }
        public string PPA_sit_hours { get; set; }
        public string PPA_sit_min { get; set; }
        public string PPA_work_days { get; set; }
        public string PPA_work { get; set; }
        public string PPA_getintobed_hour { get; set; }
        public string PPA_getintobed_minute { get; set; }
        public string PPA_getintobed_AMPM { get; set; }
        public string PPA_getoutbed_hour { get; set; }
        public string PPA_getoutbed_minute { get; set; }
        public string PPA_getoutbed_AMPM { get; set; }
        public string PPA_startwork_hour { get; set; }
        public string PPA_startwork_minute { get; set; }
        public string PPA_startwork_AMPM { get; set; }
        public string PPA_leavework_hour { get; set; }
        public string PPA_leavework_minute { get; set; }
        public string PPA_leavework_AMPM { get; set; }
        public string PPA_workhours_yourdeskperc { get; set; }
        public string PPA_workhours_awaydeskperc { get; set; }
        public string PPA_workhours_yourdeskperc_sitting { get; set; }
        public string PPA_workhours_yourdeskperc_standing { get; set; }
        public string PPA_workhours_yourdeskperc_moving { get; set; }
        public string PPA_workhours_awaydeskperc_sitting { get; set; }
        public string PPA_workhours_awaydeskperc_standing { get; set; }
        public string PPA_workhours_awaydeskperc_moving { get; set; }
        public string PPA_sit_transport_nonworkhours_workdays { get; set; }
        public string PPA_sit_transport_nonworkhours_hours { get; set; }
        public string PPA_sit_transport_nonworkhours_mininutes { get; set; }
        public string PPA_sit_transport_nonworkdays { get; set; }
        public string PPA_sit_transport_nonwork_hours { get; set; }
        public string PPA_sit_transport_nonwork_mininutes { get; set; }
        public string PPA_sit_tv_nonworkhours_workdays { get; set; }
        public string PPA_sit_tv_nonworkhours_hours { get; set; }
        public string PPA_sit_tv_nonworkhours_mininutes { get; set; }
        public string PPA_sit_tv_nonworkdays { get; set; }
        public string PPA_sit_tv_nonwork_hours { get; set; }
        public string PPA_sit_tv_nonwork_mininutes { get; set; }
        public string PPA_sit_computer_nonworkhours_workdays { get; set; }
        public string PPA_sit_computer_nonworkhours_hours { get; set; }
        public string PPA_sit_computer_nonworkhours_mininutes { get; set; }
        public string PPA_sit_computer_nonworkdays { get; set; }
        public string PPA_sit_computer_nonwork_hours { get; set; }
        public string PPA_sit_computer_nonwork_mininutes { get; set; }
        public string PPA_sit_others_nonworkhours_workdays { get; set; }
        public string PPA_sit_others_nonworkhours_hours { get; set; }
        public string PPA_sit_others_nonworkhours_mininutes { get; set; }
        public string PPA_sit_others_nonworkdays { get; set; }
        public string PPA_sit_others_nonwork_hours { get; set; }
        public string PPA_sit_others_nonwork_mininutes { get; set; }
        public string PD_eat_vegetables { get; set; }
        public string PD_eat_by_ordering { get; set; }
        public string PD_eat_fruit { get; set; }
        public string PD_eat_cake { get; set; }
        public string PD_eat_sugary_drinks { get; set; }
        public string PD_eat_fullfat_spread { get; set; }
        public string PD_eat_fullfat_cheese { get; set; }
        public string PD_eat_processed_meat { get; set; }
        public string PD_eat_savory_food { get; set; }
        public string PD_eat_savory_pastry { get; set; }
        public string PD_eat_fast_food { get; set; }
        public string PD_eat_meal_at_home { get; set; }
        public string PD_eat_pudding { get; set; }
        public string PD_eat_oilyfish { get; set; }
        public string PD_eat_regular_meals { get; set; }
        public string PD_eat_breakfast { get; set; }
        public string PD_eat_snack_between_meals { get; set; }
        public string PD_eat_portion_bread { get; set; }
        public string PD_eat_highfiber_bread { get; set; }
        public string PD_eat_bowl_breakfast { get; set; }
        public string PD_eat_bowl_highfiber { get; set; }
        public string PD_milk_type { get; set; }
        public string PD_milk_type_others { get; set; }
        public string PD_weight_concern { get; set; }
        public string PD_important_change_diet { get; set; }
        public string PD_confident_change_diet { get; set; }
        public string PSE_unable_to_control { get; set; }
        public string PSE_handle_problem { get; set; }
        public string PSE_yourway { get; set; }
        public string PSE_difficulty_handle_problem { get; set; }
        public string PSE_little_interest { get; set; }
        public string PSE_depressed { get; set; }
        public string PSE_sleeping_toomuch { get; set; }
        public string PSE_little_energy { get; set; }
        public string PSE_overeating { get; set; }
        public string PSE_feelingbad { get; set; }
        public string PSE_concentrating_trouble { get; set; }
        public string PSE_restless { get; set; }
        public string PSE_dead_thoughts { get; set; }
        public string PSE_get_along { get; set; }
        public string PSH_falling_asleep { get; set; }
        public string PSH_staying_asleep { get; set; }
        public string PSH_wakeup_tooearly { get; set; }
        public string PSH_satisfied_sleep_pattern { get; set; }
        public string PSH_noticeable_sleeping_problem { get; set; }
        public string PSH_worried_sleeping_problem { get; set; }
        public string PSH_interfere_sleeping_problem { get; set; }
        public string PSS_smoked_100_cigarettes { get; set; }
        public string PSS_first_smoke_age { get; set; }
        public string PSS_first_smoke_age694_txt { get; set; }
        public string PSS_current_smoker { get; set; }
        public string PSS_quit_smoking { get; set; }
        public string PSS_quit_smoking_days_txt { get; set; }
        public string PSS_quit_smoking_week_txt { get; set; }
        public string PSS_quit_smoking_month_txt { get; set; }
        public string PSS_quit_smoking_yrs_txt { get; set; }
        public string PSS_quit_smoking_since1year { get; set; }
        public string PSS_avg_cigarettes_perday { get; set; }
        public string PSS_avg_cigarettes_perday194_txt { get; set; }
        public string PSS_cigarettes_30days { get; set; }
        public string PSS_avg_cigarettes_30days { get; set; }
        public string PSS_cigarettes_30days_number { get; set; }
        public string PSS_trying_quit_smoke { get; set; }
        public string PSS_avg_cigarettes_30days_1_94 { get; set; }
        public string his_hypertension { get; set; }
        public string his_hypertension_year { get; set; }
        public string his_Prediabetes { get; set; }
        public string his_Prediabetes_year { get; set; }
        public string his_type2diabetes { get; set; }
        public string his_type2diabetes_year { get; set; }
        public string his_Gestational_Diabetes { get; set; }
        public string his_Gestational_Diabetes_year { get; set; }
        public string his_type1diabetes { get; set; }
        public string his_type1diabetes_year { get; set; }
        public string his_highcholesterol { get; set; }
        public string his_highcholesterol_year { get; set; }
        public string his_obesity { get; set; }
        public string his_obesity_year { get; set; }
        public string his_heartdis { get; set; }
        public string his_heartdis_year { get; set; }
        public string his_cancer { get; set; }
        public string his_cancer_year { get; set; }
        public string his_osteoporosis { get; set; }
        public string his_osteoporosis_year { get; set; }
        public string his_asthma { get; set; }
        public string his_asthma_year { get; set; }
        public string his_Hypothyroidism { get; set; }
        public string his_Hypothyroidism_year { get; set; }
        public string his_Hyperthyroidism { get; set; }
        public string his_Hyperthyroidism_year { get; set; }
        public string his_Autoimmune { get; set; }
        public string his_Autoimmune_year { get; set; }
        public string his_thyroid_other { get; set; }
        public string his_thyroid_other_text { get; set; }
        public string his_thyroid_year { get; set; }
        public string his_liver { get; set; }
        public string his_liver_year { get; set; }
        public string his_arthritis { get; set; }
        public string his_arthritis_year { get; set; }
        public string his_hepatitis_type { get; set; }
        public string his_hepatitis_type_b { get; set; }
        public string his_hepatitis_year_b { get; set; }
        public string his_hepatitis_type_c { get; set; }
        public string his_hepatitis_c_year { get; set; }
        public string his_hepatitis_type_d { get; set; }
        public string his_hepatitis_d_year { get; set; }
        public string his_hepatitis_year { get; set; }
        public string his_Anxiety { get; set; }
        public string his_Anxiety_year { get; set; }
        public string his_depression { get; set; }
        public string his_depression_year { get; set; }
        public string his_Bipolar { get; set; }
        public string his_Bipolar_year { get; set; }
        public string his_Schizophrenia { get; set; }
        public string his_Schizophrenia_year { get; set; }
        public string his_PTSD { get; set; }
        public string his_PTSD_year { get; set; }
        public string his_Alzheimer { get; set; }
        public string his_Alzheimer_year { get; set; }
        public string his_Parkinson { get; set; }
        public string his_Parkinson_year { get; set; }
        public string his_Epilepsy { get; set; }
        public string his_Epilepsy_year { get; set; }
        public string his_Other_neurological { get; set; }
        public string his_Other_neurological_text { get; set; }
        public string his_Other_neurological_year { get; set; }
        public string his_Other_Psychiatric_disorder { get; set; }
        public string his_Other_Psychiatric_disorder_specify { get; set; }
        public string his_Other_Psychiatric_disorder_year { get; set; }
        public string his_covid { get; set; }
        public string his_covid_PCR { get; set; }
        public string his_covid19 { get; set; }
        public string his_covid19_Onset { get; set; }
        public string his_covid19_EndDate { get; set; }
        public string his_covid19_Pneumonia { get; set; }
        public string his_covid19_ARDS { get; set; }
        public string his_covid19_ACX { get; set; }
        public string his_covid19_AbnormalECG { get; set; }
        public string his_covid19_MVI { get; set; }
        public string his_covid19_ECMO { get; set; }
        public string his_hypertension_specify { get; set; }
        public string his_Prediabetes_specify { get; set; }
        public string PMD_Chronic_gastrointestinal { get; set; }
        public string PMD_Inflammatory_bowel { get; set; }
        public string PMD_Gastrointestinal_ulcer { get; set; }
        public string PMD_Chronic_liver { get; set; }
        public string PMD_Chronic_pancreatitis { get; set; }
        public string PMD_Chronic_kidney { get; set; }
        public string PMD_Cholelithiasis { get; set; }
        public string PMD_Endocrine_disorders { get; set; }
        public string PMD_inflammation { get; set; }
        public string complications_retinopathy { get; set; }
        public string complications_neuropathy { get; set; }
        public string complications_cva { get; set; }
        public string complications_neuropathy_other { get; set; }
        public string complications_No_proliferative { get; set; }
        public string complications_proliferative { get; set; }
        public string complications_Laser { get; set; }
        public string complications_Retinopathy_other { get; set; }
        public string complications_foot { get; set; }
        public string complications_Gangrene { get; set; }
        public string complications_numbness { get; set; }
        public string complications_Amputation { get; set; }
        public string complications_Loss_of_toe { get; set; }
        public string complications_Pain_in_calfmuscles { get; set; }
        public string complications_Circulation_peripheral_vascular { get; set; }
        public string complications_Retinopathy_other_other { get; set; }
        public string complications_tia { get; set; }
        public string complications_Stroke { get; set; }
        public string complications_onesidebody { get; set; }
        public string complications_Bleeding { get; set; }
        public string complications_Diff_speaking { get; set; }
        public string complications_Operation_on_artery { get; set; }
        public string complications_Facial_drop { get; set; }
        public string complications_Paralyzedarm { get; set; }
        public string complications_Laser_other { get; set; }
        public string complications_albumin { get; set; }
        public string complications_Albuminuria { get; set; }
        public string complications_30_29mg_24h { get; set; }
        public string complications_300_mg_24h { get; set; }
        public string complications_egfr { get; set; }
        public string complications_CABG { get; set; }
        public string complications_PCI { get; set; }
        public string complications_Arrhythmias { get; set; }
        public string complications_nephropathy { get; set; }
        public string complications_cad { get; set; }
        public string complications_other { get; set; }
        public string complications_neuropathy_other_other { get; set; }
        public string complications_Laser_other_other { get; set; }
        public string type2_egfr { get; set; }
        public string med_hypertension { get; set; }
        public string med_hypertension_year { get; set; }
        public string med_Prediabetes { get; set; }
        public string med_Prediabetes_year { get; set; }
        public string med_type2diabetes { get; set; }
        public string med_type2diabetes_year { get; set; }
        public string med_Gestational_Diabetes { get; set; }
        public string med_Gestational_Diabetes_year { get; set; }
        public string med_type1diabetes { get; set; }
        public string med_type1diabetes_year { get; set; }
        public string med_highcholesterol { get; set; }
        public string med_highcholesterol_year { get; set; }
        public string med_obesity { get; set; }
        public string med_obesity_year { get; set; }
        public string med_heartdis { get; set; }
        public string med_heartdis_year { get; set; }
        public string med_cancer { get; set; }
        public string med_cancer_year { get; set; }
        public string med_osteoporosis { get; set; }
        public string med_osteoporosis_year { get; set; }
        public string med_asthma { get; set; }
        public string med_asthma_year { get; set; }
        public string med_Hypothyroidism { get; set; }
        public string med_Hypothyroidism_year { get; set; }
        public string med_Hyperthyroidism { get; set; }
        public string med_Hyerthyroidism_year { get; set; }
        public string med_Autoimmune { get; set; }
        public string med_Autoimmune_year { get; set; }
        public string med_thyroid_other_text { get; set; }
        public string med_thyroid_year { get; set; }
        public string med_liver { get; set; }
        public string med_liver_year { get; set; }
        public string med_arthritis { get; set; }
        public string med_arthritis_year { get; set; }
        public string med_hepatitis_type { get; set; }
        public string med_hepatitis_type_b { get; set; }
        public string med_hepatitis_b_year { get; set; }
        public string med_hepatitis_type_c { get; set; }
        public string med_hepatitis_c_year { get; set; }
        public string med_hepatitis_type_d { get; set; }
        public string med_hepatitis_d_year { get; set; }
        public string med_hepatitis_year { get; set; }
        public string med_Anxiety { get; set; }
        public string med_Anxiety_year { get; set; }
        public string med_depression { get; set; }
        public string med_depression_year { get; set; }
        public string med_Bipolar { get; set; }
        public string med_Bipolar_year { get; set; }
        public string med_Schizophrenia { get; set; }
        public string med_Schizophrenia_year { get; set; }
        public string med_PTSD { get; set; }
        public string med_PTSD_year { get; set; }
        public string med_Psychiatric_other { get; set; }
        public string med_Psychiatric_other_specify { get; set; }
        public string med_Psychiatric_other_year { get; set; }
        public string med_Alzheimer { get; set; }
        public string med_Alzheimer_year { get; set; }
        public string med_Parkinson { get; set; }
        public string med_Parkinson_year { get; set; }
        public string med_Epilepsy { get; set; }
        public string med_Epilepsy_year { get; set; }
        public string med_Other_neurological { get; set; }
        public string med_Other_neurological_text { get; set; }
        public string med_Other_neurological_year { get; set; }
        public string med_inheriteddis { get; set; }
        public string med_inheriteddis_text { get; set; }
        public string med_inheriteddis_year { get; set; }
        public string med_inherited_disease { get; set; }
        public string med_inherited_disease_specify { get; set; }
        public string med_inherited_disease_year { get; set; }
        public string med_other { get; set; }
        public string med_other_specify { get; set; }
        public string med_other_year { get; set; }
        public string allergies { get; set; }
        public string allergies_yestxt { get; set; }
        public string intolerance { get; set; }
        public string intolerance_yestxt { get; set; }
        public string med_surgery { get; set; }
        public string med_surgery_yestxt { get; set; }
        public string med_surgery_year { get; set; }
        public string medication_hypertension { get; set; }
        public string medication_hypertension_specify { get; set; }
        public string medication_hypertension_year { get; set; }
        public string medication_Prediabetes { get; set; }
        public string medication_Prediabetes_specify { get; set; }
        public string medication_Prediabetes_year { get; set; }
        public string medication_type1 { get; set; }
        public string medication_type1_specify { get; set; }
        public string medication_type1_year { get; set; }
        public string medication_type2 { get; set; }
        public string medication_type2_specify { get; set; }
        public string medication_type2_year { get; set; }
        public string medication_choles { get; set; }
        public string medication_choles_specify { get; set; }
        public string medication_choles_year { get; set; }
        public string medication_obe { get; set; }
        public string medication_obe_specify { get; set; }
        public string medication_obe_year { get; set; }
        public string medication_heart { get; set; }
        public string medication_heart_specify { get; set; }
        public string medication_heart_year { get; set; }
        public string medication_cancer { get; set; }
        public string medication_cancer_specify { get; set; }
        public string medication_cancer_year { get; set; }
        public string medication_Anxiety { get; set; }
        public string medication_Anxiety_specify { get; set; }
        public string medication_Anxiety_year { get; set; }
        public string medication_dep { get; set; }
        public string medication_dep_specify { get; set; }
        public string medication_dep_year { get; set; }
        public string medication_Bipolar { get; set; }
        public string medication_Bipolar_specify { get; set; }
        public string medication_Bipolar_year { get; set; }
        public string medication_Schizophrenia { get; set; }
        public string medication_Schizophrenia_specify { get; set; }
        public string medication_Schizophrenia_year { get; set; }
        public string medication_PTSD { get; set; }
        public string medication_PTSD_specify { get; set; }
        public string medication_PTSD_year { get; set; }
        public string medication_Other_Psychiatric_disorder { get; set; }
        public string medication_Other_Psychiatric_disorder_specify { get; set; }
        public string medication_Other_Psychiatric_disorder_year { get; set; }
        public string medication_osteo { get; set; }
        public string medication_osteo_specify { get; set; }
        public string medication_osteo_year { get; set; }
        public string medication_asth { get; set; }
        public string medication_asth_specify { get; set; }
        public string medication_asth_year { get; set; }
        public string medication_Endocrine_disorders { get; set; }
        public string medication_Endocrine_disorders_specify { get; set; }
        public string medication_Endocrine_disorders_year { get; set; }
        public string medication_migraine { get; set; }
        public string medication_migraine_specify { get; set; }
        public string medication_migraine_year { get; set; }
        public string medication_Alzheimer { get; set; }
        public string medication_Alzheimer_specify { get; set; }
        public string medication_Alzheimer_year { get; set; }
        public string medication_Parkinson { get; set; }
        public string medication_Parkinson_specify { get; set; }
        public string medication_Parkinson_year { get; set; }
        public string medication_Epilepsy { get; set; }
        public string medication_Epilepsy_specify { get; set; }
        public string medication_Epilepsy_year { get; set; }
        public string medication_Other_neurological { get; set; }
        public string medication_Other_neurological_specify { get; set; }
        public string medication_Other_neurological_year { get; set; }
        public string medication_Other { get; set; }
        public string medication_Other_specify { get; set; }
        public string medication_Other_year { get; set; }
        public string medication_none { get; set; }
        public string medication_Supplements { get; set; }
        public string donot_take_medication_specify { get; set; }
        public string donot_take_medication_year { get; set; }
        public string covid { get; set; }
        public string flu { get; set; }
        public string medication_Supplements_specify { get; set; }
        public string medication_Supplements_year { get; set; }
        public string med_vaccine { get; set; }
        public string med_flushot { get; set; }
        public string med_diagnosed_type2diabetes { get; set; }
        public string med_diagnosed_type2diabetes_year { get; set; }
        public string med_diagnosed_med_Prediabetes { get; set; }
        public string med_diagnosed_med_Prediabetes_year { get; set; }
        public string med_covid19 { get; set; }
        public string med_covid19_Onset { get; set; }
        public string med_covid19_EndDate { get; set; }
        public string med_covid19_Headache { get; set; }
        public string med_covid19_temperature { get; set; }
        public string med_covid19_Cough { get; set; }
        public string med_covid19_SoreThroat { get; set; }
        public string med_covid19_Weakness { get; set; }
        public string med_covid19_Lossofsmell { get; set; }
        public string med_covid19_Shortnessofbreath { get; set; }
        public string med_covid19_Runningnose { get; set; }
        public string med_covid19_Nausea { get; set; }
        public string med_covid19_Musclepain { get; set; }
        public string med_covid19_Diarrhea { get; set; }
        public string med_covid19_Lossoftaste { get; set; }
        public string med_hypertension_specify { get; set; }
        public string med_Prediabetes_specify { get; set; }
        public string med_type1diabetes_specify { get; set; }
        public string med_type2diabetes_specify { get; set; }
        public string med_highcholesterol_specify { get; set; }
        public string med_obesity_specify { get; set; }
        public string med_heartdis_specify { get; set; }
        public string med_cancer_Specify { get; set; }
        public string med_Anxiety_Specify { get; set; }
        public string med_depression_Specify { get; set; }
        public string med_Schizophrenia_Specify { get; set; }
        public string med_PTSD_Specify { get; set; }
        public string med_Bipolar_Specify { get; set; }
        public string med_osteoporosis_Specify { get; set; }
        public string med_asthma_Specify { get; set; }
        public string med_vaccine_Specify { get; set; }
        public string med_vaccine_Year { get; set; }


    }
}
