using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace KU.Repositories.Models
{
   // public class QuestionnaireWrap8
    //{
    //    public QuestionnaireWrap8()
    //    {
    //        result = new List<Questionnaire8>();

    //    }
    //    public IEnumerable<Questionnaire8> result { get; set; }

    //}
    public class Questionnaire8
    {
        [Key]
        public string savedformID { get; set; }
        public string Depository_ID { get; set; }
        public string sample { get; set; }
        public string projecttitle { get; set; }
        public string principalinvestigator { get; set; }
        public string collection_point { get; set; }
        public string collected_by { get; set; }
        public string collected_date { get; set; }
        public string indifamily { get; set; }
        public string family_number { get; set; }
        public string family_yes { get; set; }
        public string per_firstname { get; set; }
        public string per_middlename { get; set; }
        public string per_lastname { get; set; }
        public string gender { get; set; }
        public string emiratesid { get; set; }
        public string nationality { get; set; }
        public string dob { get; set; }
        public string PlaceOfBirth { get; set; }
        public string city { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string ethnicity { get; set; }
        public string ethnicity_mixed_specify_text { get; set; }
        public string ethnicity_others_text { get; set; }
        public string maritalstatus { get; set; }
        public string marriage_con { get; set; }
        public string pers_NumberofChildren { get; set; }
        public string pers_Boys { get; set; }
        public string pers_Girls { get; set; }
        public string pers_Numberofwives { get; set; }
        public string eduLevel { get; set; }
        public string employment_status { get; set; }
        public string BodyWeight { get; set; }
        public string Waist { get; set; }
        public string BodyMass { get; set; }
        public string Height { get; set; }
        public string hip { get; set; }
        public string bodyfatper { get; set; }
        public string bmi { get; set; }
        public string WHR { get; set; }
        public string BloodPressureSystolic { get; set; }
        public string BloodPressureDiastolic { get; set; }
        public string skincolor { get; set; }
        public string skincolor_other_text { get; set; }
        public string med_healthadvcontact { get; set; }
        public string med_healthadvcontact_othtxt { get; set; }
        public string med_annualcheck { get; set; }
        public string med_Gpvisit { get; set; }
        public string med_Gpvisit_yestxt { get; set; }
        public string med_glucosemon40 { get; set; }
        public string med_glucosemon40_othtxt { get; set; }
        public string med_hospitaladm { get; set; }
        public string med_hospitaladm_yestxt { get; set; }
        public string allergies { get; set; }
        public string allergies_yestxt { get; set; }
        public string intolerance { get; set; }
        public string intolerance_yestxt { get; set; }
        public string med_hypertension { get; set; }
        public string med_hypertension_year { get; set; }
        public string med_type2diabetes { get; set; }
        public string med_type2diabetes_year { get; set; }
        public string med_type1diabetes { get; set; }
        public string med_type1diabetes_year { get; set; }
        public string med_highcholesterol { get; set; }
        public string med_highcholesterol_year { get; set; }
        public string med_obesity { get; set; }
        public string med_obesity_year { get; set; }
        public string med_heartdis { get; set; }
        public string med_heartdis_year { get; set; }
        public string med_cancer { get; set; }
        public string med_cancer_year { get; set; }
        public string med_cancer_type { get; set; }
        public string med_depression { get; set; }
        public string med_depression_year { get; set; }
        public string med_osteoporosis { get; set; }
        public string med_osteoporosis_year { get; set; }
        public string med_asthma { get; set; }
        public string med_asthma_year { get; set; }
        public string med_inheriteddis { get; set; }
        public string med_inheriteddis_year { get; set; }
        public string med_thyroid { get; set; }
        public string med_thyroid_year { get; set; }
        public string med_liver { get; set; }
        public string med_liver_year { get; set; }
        public string med_arthritis { get; set; }
        public string med_arthritis_year { get; set; }
        public string med_hepatitis { get; set; }
        public string med_hepatitis_year { get; set; }
        public string med_sickle { get; set; }
        public string med_sickle_year { get; set; }
        public string med_neurological { get; set; }
        public string med_neurological_year { get; set; }
        public string med_faint { get; set; }
        public string med_faint_year { get; set; }
        public string med_migraine { get; set; }
        public string med_migraine_year { get; set; }
        public string med_epilepsy { get; set; }
        public string med_epilepsy_year { get; set; }
        public string med_other_specify { get; set; }
        public string med_surgery { get; set; }
        public string med_surgery_yestxt { get; set; }
        public string medication_hypertension { get; set; }
        public string medication_type1 { get; set; }
        public string medication_type2 { get; set; }
        public string medication_choles { get; set; }
        public string medication_obe { get; set; }
        public string medication_heart { get; set; }
        public string medication_cancer { get; set; }
        public string medication_dep { get; set; }
        public string medication_osteo { get; set; }
        public string medication_asth { get; set; }
        public string medication_inhdis { get; set; }
        public string medication_vit { get; set; }
        public string medication_none { get; set; }
        public string med_vaccine { get; set; }
        public string type2_complications { get; set; }
        public string type2_complications_yestxt { get; set; }
        public string type2_retinopathy { get; set; }
        public string type2_neuropathy { get; set; }
        public string type2_neuropathy_other { get; set; }
        public string type2_cva { get; set; }
        public string type2_nephropathy { get; set; }
        public string type2_egfr { get; set; }
        public string type2_cad { get; set; }
        public string type2_other { get; set; }
        public string type2_other_specify { get; set; }
        public string diabetes_mgt_none { get; set; }
        public string diabetes_mgt_tabletsonly { get; set; }
        public string diabetes_mgt_diettablets { get; set; }
        public string diabetes_mgt_diettabletsinsulin { get; set; }
        public string diabetes_mgt_dietonly { get; set; }
        public string diabetes_mgt_insulinonly { get; set; }
        public string diabetes_mgt_dietinsulin { get; set; }
        public string diabetes_mgt_unknown { get; set; }
        public string diabetes_mgt_other { get; set; }
        public string diabetes_mgt_othertxt { get; set; }
        public string BIO_FastingGlucose_RecentTest_Date { get; set; }
        public string BIO_FastingGlucose_RecentTest_Result { get; set; }
        public string BIO_FastingGlucose_LastTest_Date { get; set; }
        public string BIO_FastingGlucose_LastTest_Result { get; set; }
        public string BIO_FastingGlucose_IsNormalResult { get; set; }
        public string BIO_RandomGlucose_RecentTest_Date { get; set; }
        public string BIO_RandomGlucose_RecentTest_Result { get; set; }
        public string BIO_RandomGlucose_LastTest_Date { get; set; }
        public string BIO_RandomGlucose_LastTest_Result { get; set; }
        public string BIO_RandomGlucose_IsNormalResult { get; set; }
        public string BIO_OGTT_FBG_RecentTest_Date { get; set; }
        public string BIO_OGTT_FBG_RecentTest_Result { get; set; }
        public string BIO_OGTT_FBG_LastTest_Date { get; set; }
        public string BIO_OGTT_FBG_LastTest_Result { get; set; }
        public string BIO_OGTT_FBG_IsNormalResult { get; set; }
        public string BIO_OGTT_FBG2_RecentTest_Date { get; set; }
        public string BIO_OGTT_FBG2_RecentTest_Result { get; set; }
        public string BIO_OGTT_FBG2_LastTest_Date { get; set; }
        public string BIO_OGTT_FBG2_LastTest_Result { get; set; }
        public string BIO_OGTT_FBG2_IsNormalResult { get; set; }
        public string BIO_HbA1c_RecentTest_Date { get; set; }
        public string BIO_HbA1c_RecentTest_Result { get; set; }
        public string BIO_HbA1c_LastTest_Date { get; set; }
        public string BIO_HbA1c_LastTest_Result { get; set; }
        public string BIO_HbA1c_IsNormalResult { get; set; }
        public string BIO_TotalCholesterol_RecentTest_Date { get; set; }
        public string BIO_TotalCholesterol_RecentTest_Result { get; set; }
        public string BIO_TotalCholesterol_LastTest_Date { get; set; }
        public string BIO_TotalCholesterol_LastTest_Result { get; set; }
        public string BIO_TotalCholesterol_IsNormalResult { get; set; }
        public string BIO_Triglyceride_RecentTest_Date { get; set; }
        public string BIO_Triglyceride_RecentTest_Result { get; set; }
        public string BIO_Triglyceride_LastTest_Date { get; set; }
        public string BIO_Triglyceride_LastTest_Result { get; set; }
        public string BIO_Triglyceride_IsNormalResult { get; set; }
        public string BIO_HDL_RecentTest_Date { get; set; }
        public string BIO_HDL_RecentTest_Result { get; set; }
        public string BIO_HDL_LastTest_Date { get; set; }
        public string BIO_HDL_LastTest_Result { get; set; }
        public string BIO_HDL_IsNormalResult { get; set; }
        public string BIO_LDL_RecentTest_Date { get; set; }
        public string BIO_LDL_RecentTest_Result { get; set; }
        public string BIO_LDL_LastTest_Date { get; set; }
        public string BIO_LDL_LastTest_Result { get; set; }
        public string BIO_LDL_IsNormalResult { get; set; }
        public string BIO_Microalbumin_RecentTest_Date { get; set; }
        public string BIO_Microalbumin_RecentTest_Result { get; set; }
        public string BIO_Microalbumin_LastTest_Date { get; set; }
        public string BIO_Microalbumin_LastTest_Result { get; set; }
        public string BIO_Microalbumin_IsNormalResult { get; set; }
        public string BIO_albuminuria_RecentTest_Date { get; set; }
        public string BIO_albuminuria_RecentTest_Result { get; set; }
        public string BIO_albuminuria_LastTest_Date { get; set; }
        public string BIO_albuminuria_LastTest_Result { get; set; }
        public string BIO_albuminuria_IsNormalResult { get; set; }
        public string BIO_albumincreatinine_RecentTest_Date { get; set; }
        public string BIO_albumincreatinine_RecentTest_Result { get; set; }
        public string BIO_albumincreatinine_LastTest_Date { get; set; }
        public string BIO_albumincreatinine_LastTest_Result { get; set; }
        public string BIO_albumincreatinine_IsNormalResult { get; set; }
        public string BIO_Creatinine_RecentTest_Date { get; set; }
        public string BIO_Creatinine_RecentTest_Result { get; set; }
        public string BIO_Creatinine_LastTest_Date { get; set; }
        public string BIO_Creatinine_LastTest_Result { get; set; }
        public string BIO_Creatinine_IsNormalResult { get; set; }
        public string BIO_Urea_RecentTest_Date { get; set; }
        public string BIO_Urea_RecentTest_Result { get; set; }
        public string BIO_Urea_LastTest_Date { get; set; }
        public string BIO_Urea_LastTest_Result { get; set; }
        public string BIO_Urea_IsNormalResult { get; set; }
        public string BIO_VitaminDLevel_RecentTest_Date { get; set; }
        public string BIO_VitaminDLevel_RecentTest_Result { get; set; }
        public string BIO_VitaminDLevel_LastTest_Date { get; set; }
        public string BIO_VitaminDLevel_LastTest_Result { get; set; }
        public string BIO_VitaminDLevel_IsNormalResult { get; set; }
        public string BIO_egfr_RecentTest_Date { get; set; }
        public string BIO_egfr_RecentTest_Result { get; set; }
        public string BIO_egfr_LastTest_Date { get; set; }
        public string BIO_egfr_LastTest_Result { get; set; }
        public string BIO_egfr_IsNormalResult { get; set; }
        public string BIO_sodium_RecentTest_Date { get; set; }
        public string BIO_sodium_RecentTest_Result { get; set; }
        public string BIO_sodium_LastTest_Date { get; set; }
        public string BIO_sodium_LastTest_Result { get; set; }
        public string BIO_sodium_IsNormalResult { get; set; }
        public string BIO_potassium_RecentTest_Date { get; set; }
        public string BIO_potassium_RecentTest_Result { get; set; }
        public string BIO_potassium_LastTest_Date { get; set; }
        public string BIO_potassium_LastTest_Result { get; set; }
        public string BIO_potassium_IsNormalResult { get; set; }
        public string BIO_calcium_RecentTest_Date { get; set; }
        public string BIO_calcium_RecentTest_Result { get; set; }
        public string BIO_calcium_LastTest_Date { get; set; }
        public string BIO_calcium_LastTest_Result { get; set; }
        public string BIO_calcium_IsNormalResult { get; set; }
        public string BIO_mag_RecentTest_Date { get; set; }
        public string BIO_mag_RecentTest_Result { get; set; }
        public string BIO_mag_LastTest_Date { get; set; }
        public string BIO_mag_LastTest_Result { get; set; }
        public string BIO_mag_IsNormalResult { get; set; }
        public string BIO_phos_RecentTest_Date { get; set; }
        public string BIO_phos_RecentTest_Result { get; set; }
        public string BIO_phos_LastTest_Date { get; set; }
        public string BIO_phos_LastTest_Result { get; set; }
        public string BIO_phos_IsNormalResult { get; set; }
        public string BIO_bicar_RecentTest_Date { get; set; }
        public string BIO_bicar_RecentTest_Result { get; set; }
        public string BIO_bicar_LastTest_Date { get; set; }
        public string BIO_bicar_LastTest_Result { get; set; }
        public string BIO_bicar_IsNormalResult { get; set; }
        public string BIO_protein_RecentTest_Date { get; set; }
        public string BIO_protein_RecentTest_Result { get; set; }
        public string BIO_protein_LastTest_Date { get; set; }
        public string BIO_protein_LastTest_Result { get; set; }
        public string BIO_protein_IsNormalResult { get; set; }
        public string BIO_serum_RecentTest_Date { get; set; }
        public string BIO_serum_RecentTest_Result { get; set; }
        public string BIO_serum_LastTest_Date { get; set; }
        public string BIO_serum_LastTest_Result { get; set; }
        public string BIO_serum_IsNormalResult { get; set; }
        public string BIO_cprotein_RecentTest_Date { get; set; }
        public string BIO_cprotein_RecentTest_Result { get; set; }
        public string BIO_cprotein_LastTest_Date { get; set; }
        public string BIO_cprotein_LastTest_Result { get; set; }
        public string BIO_cprotein_IsNormalResult { get; set; }
        public string BIO_alt_RecentTest_Date { get; set; }
        public string BIO_alt_RecentTest_Result { get; set; }
        public string BIO_alt_LastTest_Date { get; set; }
        public string BIO_alt_LastTest_Result { get; set; }
        public string BIO_alt_IsNormalResult { get; set; }
        public string BIO_alp_RecentTest_Date { get; set; }
        public string BIO_alp_RecentTest_Result { get; set; }
        public string BIO_alp_LastTest_Date { get; set; }
        public string BIO_alp_LastTest_Result { get; set; }
        public string BIO_alp_IsNormalResult { get; set; }
        public string BIO_ast_RecentTest_Date { get; set; }
        public string BIO_ast_RecentTest_Result { get; set; }
        public string BIO_ast_LastTest_Date { get; set; }
        public string BIO_ast_LastTest_Result { get; set; }
        public string BIO_ast_IsNormalResult { get; set; }
        public string BIO_bilirubin_RecentTest_Date { get; set; }
        public string BIO_bilirubin_RecentTest_Result { get; set; }
        public string BIO_bilirubin_LastTest_Date { get; set; }
        public string BIO_bilirubin_LastTest_Result { get; set; }
        public string BIO_bilirubin_IsNormalResult { get; set; }
        public string BIO_t3_RecentTest_Date { get; set; }
        public string BIO_t3_RecentTest_Result { get; set; }
        public string BIO_t3_LastTest_Date { get; set; }
        public string BIO_t3_LastTest_Result { get; set; }
        public string BIO_t3_IsNormalResult { get; set; }
        public string BIO_t4_RecentTest_Date { get; set; }
        public string BIO_t4_RecentTest_Result { get; set; }
        public string BIO_t4_LastTest_Date { get; set; }
        public string BIO_t4_LastTest_Result { get; set; }
        public string BIO_t4_IsNormalResult { get; set; }
        public string BIO_freet4_RecentTest_Date { get; set; }
        public string BIO_freet4_RecentTest_Result { get; set; }
        public string BIO_freet4_LastTest_Date { get; set; }
        public string BIO_freet4_LastTest_Result { get; set; }
        public string BIO_freet4_IsNormalResult { get; set; }
        public string BIO_tsh_RecentTest_Date { get; set; }
        public string BIO_tsh_RecentTest_Result { get; set; }
        public string BIO_tsh_LastTest_Date { get; set; }
        public string BIO_tsh_LastTest_Result { get; set; }
        public string BIO_tsh_IsNormalResult { get; set; }
        public string BIO_parathyroid_RecentTest_Date { get; set; }
        public string BIO_parathyroid_RecentTest_Result { get; set; }
        public string BIO_parathyroid_LastTest_Date { get; set; }
        public string BIO_parathyroid_LastTest_Result { get; set; }
        public string BIO_parathyroid_IsNormalResult { get; set; }
        public string BIO_wbc_RecentTest_Date { get; set; }
        public string BIO_wbc_RecentTest_Result { get; set; }
        public string BIO_wbc_LastTest_Date { get; set; }
        public string BIO_wbc_LastTest_Result { get; set; }
        public string BIO_wbc_IsNormalResult { get; set; }
        public string BIO_wbc_diff_RecentTest_Date { get; set; }
        public string BIO_wbc_diff_RecentTest_Result { get; set; }
        public string BIO_wbc_diff_LastTest_Date { get; set; }
        public string BIO_wbc_diff_LastTest_Result { get; set; }
        public string BIO_wbc_diff_IsNormalResult { get; set; }
        public string BIO_rbc_RecentTest_Date { get; set; }
        public string BIO_rbc_RecentTest_Result { get; set; }
        public string BIO_rbc_LastTest_Date { get; set; }
        public string BIO_rbc_LastTest_Result { get; set; }
        public string BIO_rbc_IsNormalResult { get; set; }
        public string BIO_haemoglobin_RecentTest_Date { get; set; }
        public string BIO_haemoglobin_RecentTest_Result { get; set; }
        public string BIO_haemoglobin_LastTest_Date { get; set; }
        public string BIO_haemoglobin_LastTest_Result { get; set; }
        public string BIO_haemoglobin_IsNormalResult { get; set; }
        public string BIO_haematocrit_RecentTest_Date { get; set; }
        public string BIO_haematocrit_RecentTest_Result { get; set; }
        public string BIO_haematocrit_LastTest_Date { get; set; }
        public string BIO_haematocrit_LastTest_Result { get; set; }
        public string BIO_haematocrit_IsNormalResult { get; set; }
        public string BIO_ferritin_RecentTest_Date { get; set; }
        public string BIO_ferritin_RecentTest_Result { get; set; }
        public string BIO_ferritin_LastTest_Date { get; set; }
        public string BIO_ferritin_LastTest_Result { get; set; }
        public string BIO_ferritin_IsNormalResult { get; set; }
        public string BIO_rdw_RecentTest_Date { get; set; }
        public string BIO_rdw_RecentTest_Result { get; set; }
        public string BIO_rdw_LastTest_Date { get; set; }
        public string BIO_rdw_LastTest_Result { get; set; }
        public string BIO_rdw_IsNormalResult { get; set; }
        public string BIO_rbcmcv_RecentTest_Date { get; set; }
        public string BIO_rbcmcv_RecentTest_Result { get; set; }
        public string BIO_rbcmcv_LastTest_Date { get; set; }
        public string BIO_rbcmcv_LastTest_Result { get; set; }
        public string BIO_rbcmcv_IsNormalResult { get; set; }
        public string BIO_rbcmch_RecentTest_Date { get; set; }
        public string BIO_rbcmch_RecentTest_Result { get; set; }
        public string BIO_rbcmch_LastTest_Date { get; set; }
        public string BIO_rbcmch_LastTest_Result { get; set; }
        public string BIO_rbcmch_IsNormalResult { get; set; }
        public string BIO_rbcmchc_RecentTest_Date { get; set; }
        public string BIO_rbcmchc_RecentTest_Result { get; set; }
        public string BIO_rbcmchc_LastTest_Date { get; set; }
        public string BIO_rbcmchc_LastTest_Result { get; set; }
        public string BIO_rbcmchc_IsNormalResult { get; set; }
        public string BIO_Reticulocyte_RecentTest_Date { get; set; }
        public string BIO_Reticulocyte_RecentTest_Result { get; set; }
        public string BIO_Reticulocyte_LastTest_Date { get; set; }
        public string BIO_Reticulocyte_LastTest_Result { get; set; }
        public string BIO_Reticulocyte_IsNormalResult { get; set; }
        public string BIO_Platelet_RecentTest_Date { get; set; }
        public string BIO_Platelet_RecentTest_Result { get; set; }
        public string BIO_Platelet_LastTest_Date { get; set; }
        public string BIO_Platelet_LastTest_Result { get; set; }
        public string BIO_Platelet_IsNormalResult { get; set; }
        public string BIO_mpv_RecentTest_Date { get; set; }
        public string BIO_mpv_RecentTest_Result { get; set; }
        public string BIO_mpv_LastTest_Date { get; set; }
        public string BIO_mpv_LastTest_Result { get; set; }
        public string BIO_mpv_IsNormalResult { get; set; }
        public string BIO_UTSmacroscopic_RecentTest_Date { get; set; }
        public string BIO_UTSmacroscopic_RecentTest_Result { get; set; }
        public string BIO_UTSmacroscopic_LastTest_Date { get; set; }
        public string BIO_UTSmacroscopic_LastTest_Result { get; set; }
        public string BIO_UTSmacroscopic_IsNormalResult { get; set; }
        public string BIO_UTSph_RecentTest_Date { get; set; }
        public string BIO_UTSph_RecentTest_Result { get; set; }
        public string BIO_UTSph_LastTest_Date { get; set; }
        public string BIO_UTSph_LastTest_Result { get; set; }
        public string BIO_UTSph_IsNormalResult { get; set; }
        public string BIO_UTSglu_RecentTest_Date { get; set; }
        public string BIO_UTSglu_RecentTest_Result { get; set; }
        public string BIO_UTSglu_LastTest_Date { get; set; }
        public string BIO_UTSglu_LastTest_Result { get; set; }
        public string BIO_UTSglu_IsNormalResult { get; set; }
        public string BIO_UTSgravity_RecentTest_Date { get; set; }
        public string BIO_UTSgravity_RecentTest_Result { get; set; }
        public string BIO_UTSgravity_LastTest_Date { get; set; }
        public string BIO_UTSgravity_LastTest_Result { get; set; }
        public string BIO_UTSgravity_IsNormalResult { get; set; }
        public string BIO_UTSNitrite_RecentTest_Date { get; set; }
        public string BIO_UTSNitrite_RecentTest_Result { get; set; }
        public string BIO_UTSNitrite_LastTest_Date { get; set; }
        public string BIO_UTSNitrite_LastTest_Result { get; set; }
        public string BIO_UTSNitrite_IsNormalResult { get; set; }
        public string BIO_UTSLeukocyte_RecentTest_Date { get; set; }
        public string BIO_UTSLeukocyte_RecentTest_Result { get; set; }
        public string BIO_UTSLeukocyte_LastTest_Date { get; set; }
        public string BIO_UTSLeukocyte_LastTest_Result { get; set; }
        public string BIO_UTSLeukocyte_IsNormalResult { get; set; }
        public string BIO_UTSMicrocells_RecentTest_Date { get; set; }
        public string BIO_UTSMicrocells_RecentTest_Result { get; set; }
        public string BIO_UTSMicrocells_LastTest_Date { get; set; }
        public string BIO_UTSMicrocells_LastTest_Result { get; set; }
        public string BIO_UTSMicrocells_IsNormalResult { get; set; }
        public string BIO_UTSMicrocasts_RecentTest_Date { get; set; }
        public string BIO_UTSMicrocasts_RecentTest_Result { get; set; }
        public string BIO_UTSMicrocasts_LastTest_Date { get; set; }
        public string BIO_UTSMicrocasts_LastTest_Result { get; set; }
        public string BIO_UTSMicrocasts_IsNormalResult { get; set; }
        public string BIO_UTSMicrocrystals_RecentTest_Date { get; set; }
        public string BIO_UTSMicrocrystals_RecentTest_Result { get; set; }
        public string BIO_UTSMicrocrystals_LastTest_Date { get; set; }
        public string BIO_UTSMicrocrystals_LastTest_Result { get; set; }
        public string BIO_UTSMicrocrystals_IsNormalResult { get; set; }
        public string life_smokingstatus { get; set; }
        public string Walk { get; set; }
        public string Walk_IfYes { get; set; }
        public string Walk_others_Specify { get; set; }
        public string walking_intensity { get; set; }
        public string healthy_diet { get; set; }
        public string diet_other { get; set; }
        public string weight_change { get; set; }
        public string spl_diet { get; set; }
        public string fastfood_intake { get; set; }
        public string fruits_veg { get; set; }
        public string softdrinks { get; set; }
        public string eat_after_midnight { get; set; }
        public string satisfied_body { get; set; }
        public string happy_life { get; set; }
        public string healthy_individual { get; set; }
        public string fam_fatethnicity { get; set; }
        public string fam_fatethnicity_other { get; set; }
        public string fam_fatplaceofbirth { get; set; }
        public string fam_motethnicity { get; set; }
        public string fam_motethnicity_other { get; set; }
        public string fam_motplaceofbirth { get; set; }
        public string fam_parents_related { get; set; }
        public string fam_parents_related_yes { get; set; }
        public string fam_hypertension { get; set; }
        public string fam_heart { get; set; }
        public string fam_dep { get; set; }
        public string fam_osteo { get; set; }
        public string fam_type1 { get; set; }
        public string fam_type2 { get; set; }
        public string fam_gesdia { get; set; }
        public string fam_cancer { get; set; }
        public string fam_condition_cancer_type { get; set; }
        public string fam_other { get; set; }
        public string fam_condition_other { get; set; }
        public string fam_pedigree { get; set; }
        public string lab_sample_type_blood { get; set; }
        public string lab_sample_type_saliva { get; set; }
        public string lab_sample_type_tissue { get; set; }
        public string lab_sample_type_other { get; set; }
        public string lab_sample_type_other_text { get; set; }
        public string lab_sample_date { get; set; }
        public string lab_storage { get; set; }
        public string lab_sample_volume { get; set; }
        public string lab_project_code { get; set; }
        public string lab_test_code { get; set; }
        public string lab_comments { get; set; }
        public string inhibit_ace { get; set; }
        public string perindop { get; set; }
        public string captopril { get; set; }
        public string enalapril { get; set; }
        public string lisinop { get; set; }
        public string medications_others { get; set; }
        public string anti_hyper_arbs { get; set; }
        public string losartan { get; set; }
        public string Valsartan { get; set; }
        public string anti_dose { get; set; }
        public string beta_blockers { get; set; }
        public string atenolol { get; set; }
        public string bisopr { get; set; }
        public string beta_other_dose { get; set; }
        public string diurectics { get; set; }
        public string indapam { get; set; }
        public string hydroch { get; set; }
        public string fruse { get; set; }
        public string diur_others_dose { get; set; }
        public string CA_channel_blockers { get; set; }
        public string amlodip { get; set; }
        public string nifedip { get; set; }
        public string verapamil { get; set; }
        public string ca_channer_others { get; set; }
        public string others_oh { get; set; }
        public string methyldop { get; set; }
        public string anti_hyper_others_dose { get; set; }
        public string Anti_Dyslipidemia_statins { get; set; }
        public string simvast { get; set; }
        public string atorvast { get; set; }
        public string rosuvas { get; set; }
        public string Anti_Dyslipidemia_OtherD { get; set; }
        public string Anti_Dyslipidemia_fibrates { get; set; }
        public string gemfib { get; set; }
        public string fenofib { get; set; }
        public string fibrat1 { get; set; }
        public string fibrat2 { get; set; }
        public string Anti_Dyslipidemia_others { get; set; }
        public string AntiOthers { get; set; }
        public string anti_hyper_Biguanides { get; set; }
        public string Metformin { get; set; }
        public string anti_hyper_sus { get; set; }
        public string glibenclamide { get; set; }
        public string glimepir { get; set; }
        public string glipizide { get; set; }
        public string gliclazide_mr { get; set; }
        public string glipizide_dose { get; set; }
        public string pride_dose { get; set; }
        public string anti_hyper_other_su { get; set; }
        public string anti_hyper_thiazolid { get; set; }
        public string pioglit { get; set; }
        public string anti_hyper_thiazolid_Other { get; set; }
        public string anti_hyper_meglitin { get; set; }
        public string anti_hyper_Nateglinide { get; set; }
        public string anti_hyper_repaglin { get; set; }
        public string anti_hyper_glucosid { get; set; }
        public string acarbose { get; set; }
        public string anti_hyper_dipeptidyl { get; set; }
        public string anti_hyper_sitaglip { get; set; }
        public string anti_hyper_vildaglip { get; set; }
        public string anti_hyper_saxaglip { get; set; }
        public string anti_hyper_linaglip { get; set; }
        public string anti_hyper_peptid_others { get; set; }
        public string pramlintide { get; set; }
        public string anti_hyper_other_peptid { get; set; }
        public string anti_hyper_incretinm { get; set; }
        public string anti_hyper_exenatide { get; set; }
        public string anti_hyper_liraglut { get; set; }
        public string exenatide_dose { get; set; }
        public string anti_hyper_insulin_lin { get; set; }
        public string lispro_dose { get; set; }
        public string aspart_dose { get; set; }
        public string glulisine_dose { get; set; }
        public string regular_dose { get; set; }
        public string nph_dose { get; set; }
        public string Detemir_Dose { get; set; }
        public string glargine { get; set; }
        public string anti_hyper_insulin_lin_combination { get; set; }
        public string suplements_vitamind3 { get; set; }
        public string suplements_OtherVit { get; set; }
        public string anti_depre_prozac_dose { get; set; }
        public string anti_depre_other_dose { get; set; }
        public string anti_anx_diazepam_dose { get; set; }
        public string anti_anx_other_dose { get; set; }
        public string medication_other_dose { get; set; }
        public string traditional_chinese { get; set; }
    }
}
