using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace KU.Repositories.Models
{
   // public class QuestionnaireWrap9_9
    //{
    //    public QuestionnaireWrap9_9()
    //    {
    //        result = new List<Questionnaire9_9>();

    //    }
    //    public IEnumerable<Questionnaire9_9> result { get; set; }

    //}
    public class Questionnaire9_9
    {
        [Key]
        public string savedformID { get; set; }
        public string sample { get; set; }
        public string projecttitle { get; set; }
        public string principalinvestigator { get; set; }
        public string collection_point { get; set; }
        public string collected_date { get; set; }
        public string gender { get; set; }
        public string age { get; set; }
        public string dob { get; set; }
        public string nationality { get; set; }
        public string PlaceOfBirth { get; set; }
        public string city { get; set; }
        public string ethnicity { get; set; }
        public string ethnicity_others_text { get; set; }
        public string maritalstatus { get; set; }
        public string pers_Numberofwives { get; set; }
        public string marriage_con { get; set; }
        public string pers_NumberofChildren { get; set; }
        public string pers_Boys { get; set; }
        public string pers_Girls { get; set; }
        public string pers_BoysGirls { get; set; }
        public string eduGradel { get; set; }
        public string eduLevel { get; set; }
        public string household { get; set; }
        public string household_minor { get; set; }
        public string ownresidence { get; set; }
        public string employment_status { get; set; }
        public string employment_work { get; set; }
        public string employment_nightshift { get; set; }
        public string employment_nightshift_others { get; set; }
        public string BIO_date { get; set; }
        public string BIO_FastingGlucose_before_medication { get; set; }
        public string BIO_FastingGlucose_Result_after3 { get; set; }
        public string BIO_FastingGlucose_result_after6 { get; set; }
        public string BIO_FastingGlucose_result_after9 { get; set; }
        public string BIO_FastingGlucose_result_after12 { get; set; }
        public string BIO_RandomGlucose_before_medication { get; set; }
        public string BIO_RandomGlucose_result_after3 { get; set; }
        public string BIO_RandomGlucose_result_after6 { get; set; }
        public string BIO_RandomGlucose_result_after9 { get; set; }
        public string BIO_RandomGlucose_result_after12 { get; set; }
        public string BIO_OGTT_before_medication { get; set; }
        public string BIO_OGTT_result_after3 { get; set; }
        public string BIO_OGTT_result_after6 { get; set; }
        public string BIO_OGTT_result_after9 { get; set; }
        public string BIO_OGTT_result_after12 { get; set; }
        public string BIO_FG2_before_medication { get; set; }
        public string BIO_FG2_result_after3 { get; set; }
        public string BIO_FG2_result_after6 { get; set; }
        public string BIO_FG2_result_after9 { get; set; }
        public string BIO_FG2_result_after12 { get; set; }
        public string BIO_HbA1c_before_medication { get; set; }
        public string BIO_HbA1c_result_after3 { get; set; }
        public string BIO_HbA1c_result_after6 { get; set; }
        public string BIO_HbA1c_result_after9 { get; set; }
        public string BIO_HbA1c_result_after12 { get; set; }
        public string BIO_Fasting_insulin_before_medication { get; set; }
        public string BIO_Fasting_insulin_result_after3 { get; set; }
        public string BIO_Fasting_insulin_result_after6 { get; set; }
        public string BIO_Fasting_insulin_result_after9 { get; set; }
        public string BIO_Fasting_insulin_result_after12 { get; set; }
        public string BIO_TotalCholesterol_before_medication { get; set; }
        public string BIO_TotalCholesterol_result_after3 { get; set; }
        public string BIO_TotalCholesterol_result_after6 { get; set; }
        public string BIO_TotalCholesterol_result_after9 { get; set; }
        public string BIO_TotalCholesterol_result_after12 { get; set; }
        public string BIO_Triglyceride_before_medication { get; set; }
        public string BIO_Triglyceride_result_after3 { get; set; }
        public string BIO_Triglyceride_result_after6 { get; set; }
        public string BIO_Triglyceride_result_after9 { get; set; }
        public string BIO_Triglyceride_result_after12 { get; set; }
        public string BIO_HDL_before_medication { get; set; }
        public string BIO_HDL_result_after3 { get; set; }
        public string BIO_HDL_result_after6 { get; set; }
        public string BIO_HDL_result_after9 { get; set; }
        public string BIO_HDL_result_after12 { get; set; }
        public string BIO_LDL_before_medication { get; set; }
        public string BIO_LDL_result_after3 { get; set; }
        public string BIO_LDL_result_after6 { get; set; }
        public string BIO_LDL_result_after9 { get; set; }
        public string BIO_LDL_result_after12 { get; set; }
        public string BIO_VitaminDLevel_before_medication { get; set; }
        public string BIO_VitaminDLevel_result_after3 { get; set; }
        public string BIO_VitaminDLevel_result_after6 { get; set; }
        public string BIO_VitaminDLevel_result_after9 { get; set; }
        public string BIO_VitaminDLevel_result_after12 { get; set; }
        public string BIO_Microalbumin_before_medication { get; set; }
        public string BIO_Microalbumin_result_after3 { get; set; }
        public string BIO_Microalbumin_result_after6 { get; set; }
        public string BIO_Microalbumin_result_after9 { get; set; }
        public string BIO_Microalbumin_result_after12 { get; set; }
        public string BIO_albuminuria_before_medication { get; set; }
        public string BIO_albuminuria_result_after3 { get; set; }
        public string BIO_albuminuria_result_after6 { get; set; }
        public string BIO_albuminuria_result_after9 { get; set; }
        public string BIO_albuminuria_result_after12 { get; set; }
        public string BIO_albumincreatinine_before_medication { get; set; }
        public string BIO_albumincreatinine_result_after3 { get; set; }
        public string BIO_albumincreatinine_result_after6 { get; set; }
        public string BIO_albumincreatinine_result_after9 { get; set; }
        public string BIO_albumincreatinine_result_after12 { get; set; }
        public string BIO_Creatinine_before_medication { get; set; }
        public string BIO_Creatinine_result_after3 { get; set; }
        public string BIO_Creatinine_result_after6 { get; set; }
        public string BIO_Creatinine_result_after9 { get; set; }
        public string BIO_Creatinine_result_after12 { get; set; }
        public string BIO_Urea_before_medication { get; set; }
        public string BIO_Urea_result_after3 { get; set; }
        public string BIO_Urea_result_after6 { get; set; }
        public string BIO_Urea_result_after9 { get; set; }
        public string BIO_Urea_result_after12 { get; set; }
        public string BIO_egfr_before_medication { get; set; }
        public string BIO_egfr_result_after3 { get; set; }
        public string BIO_egfr_result_after6 { get; set; }
        public string BIO_egfr_result_after9 { get; set; }
        public string BIO_egfr_result_after12 { get; set; }
        public string BIO_sodium_before { get; set; }
        public string BIO_sodium_result_after3 { get; set; }
        public string BIO_sodium_result_after6 { get; set; }
        public string BIO_sodium_result_after9 { get; set; }
        public string BIO_sodium_result_after12 { get; set; }
        public string BIO_potassium_before { get; set; }
        public string BIO_potassium_result_after3 { get; set; }
        public string BIO_potassium_result_after6 { get; set; }
        public string BIO_potassium_result_after9 { get; set; }
        public string BIO_potassium_result_after12 { get; set; }
        public string BIO_calcium_before { get; set; }
        public string BIO_calcium_result_after3 { get; set; }
        public string BIO_calcium_result_after6 { get; set; }
        public string BIO_calcium_result_after9 { get; set; }
        public string BIO_calcium_result_after12 { get; set; }
        public string BIO_Magnesium_before { get; set; }
        public string BIO_Magnesium_result_after3 { get; set; }
        public string BIO_Magnesium_result_after6 { get; set; }
        public string BIO_Magnesium_result_after9 { get; set; }
        public string BIO_Magnesium_result_after12 { get; set; }
        public string BIO_Phosphorus_before { get; set; }
        public string BIO_Phosphorus_result_after3 { get; set; }
        public string BIO_Phosphorus_result_after6 { get; set; }
        public string BIO_Phosphorus_result_after9 { get; set; }
        public string BIO_Phosphorus_result_after12 { get; set; }
        public string BIO_Bicarbonate_before { get; set; }
        public string BIO_Bicarbonate_result_after3 { get; set; }
        public string BIO_Bicarbonate_result_after6 { get; set; }
        public string BIO_Bicarbonate_result_after9 { get; set; }
        public string BIO_Bicarbonate_result_after12 { get; set; }
        public string BIO_ALT_before { get; set; }
        public string BIO_ALT_result_after3 { get; set; }
        public string BIO_ALT_result_after6 { get; set; }
        public string BIO_ALT_result_after9 { get; set; }
        public string BIO_ALT_result_after12 { get; set; }
        public string BIO_ALP_before { get; set; }
        public string BIO_ALP_result_after3 { get; set; }
        public string BIO_ALP_result_after6 { get; set; }
        public string BIO_ALP_result_after9 { get; set; }
        public string BIO_ALP_result_after12 { get; set; }
        public string BIO_AST_before { get; set; }
        public string BIO_AST_result_after3 { get; set; }
        public string BIO_AST_result_after6 { get; set; }
        public string BIO_AST_result_after9 { get; set; }
        public string BIO_AST_result_after12 { get; set; }
        public string BIO_bilirubin_before { get; set; }
        public string BIO_bilirubin_result_after3 { get; set; }
        public string BIO_bilirubin_result_after6 { get; set; }
        public string BIO_bilirubin_result_after9 { get; set; }
        public string BIO_bilirubin_result_after12 { get; set; }
        public string BIO_Protein_before { get; set; }
        public string BIO_Protein_result_after3 { get; set; }
        public string BIO_Protein_result_after6 { get; set; }
        public string BIO_Protein_result_after9 { get; set; }
        public string BIO_Protein_result_after12 { get; set; }
        public string BIO_Serum_albumin_before { get; set; }
        public string BIO_Serum_albumin_result_after3 { get; set; }
        public string BIO_Serum_albumin_result_after6 { get; set; }
        public string BIO_Serum_albumin_result_after9 { get; set; }
        public string BIO_Serum_albumin_result_after12 { get; set; }
        public string BIO_cprotein_before { get; set; }
        public string BIO_cprotein_result_after3 { get; set; }
        public string BIO_cprotein_result_after6 { get; set; }
        public string BIO_cprotein_result_after9 { get; set; }
        public string BIO_cprotein_result_after12 { get; set; }
        public string BIO_Fibrinogen_before { get; set; }
        public string BIO_Fibrinogen_result_after3 { get; set; }
        public string BIO_Fibrinogen_result_after6 { get; set; }
        public string BIO_Fibrinogen_result_after9 { get; set; }
        public string BIO_Fibrinogen_result_after12 { get; set; }
        public string BIO_Interleukin_before { get; set; }
        public string BIO_Interleukin_result_after3 { get; set; }
        public string BIO_Interleukin_result_after6 { get; set; }
        public string BIO_Interleukin_result_after9 { get; set; }
        public string BIO_Interleukin_result_after12 { get; set; }
        public string BIO_Procalcitonin_before { get; set; }
        public string BIO_Procalcitonin_result_after3 { get; set; }
        public string BIO_Procalcitonin_result_after6 { get; set; }
        public string BIO_Procalcitonin_result_after9 { get; set; }
        public string BIO_Procalcitonin_result_after12 { get; set; }
        public string BIO_PAI1_before { get; set; }
        public string BIO_PAI1_result_after3 { get; set; }
        public string BIO_PAI1_result_after6 { get; set; }
        public string BIO_PAI1_result_after9 { get; set; }
        public string BIO_PAI1_result_after12 { get; set; }
        public string BIO_Insulin_before { get; set; }
        public string BIO_Insulin_result_after3 { get; set; }
        public string BIO_Insulin_result_after6 { get; set; }
        public string BIO_Insulin_result_after9 { get; set; }
        public string BIO_Insulin_result_after12 { get; set; }
        public string BIO_Cortisol_before { get; set; }
        public string BIO_Cortisol_result_after3 { get; set; }
        public string BIO_Cortisol_result_after6 { get; set; }
        public string BIO_Cortisol_result_after9 { get; set; }
        public string BIO_Cortisol_result_after12 { get; set; }
        public string BIO_T3_before { get; set; }
        public string BIO_T3_result_after3 { get; set; }
        public string BIO_T3_result_after6 { get; set; }
        public string BIO_T3_result_after9 { get; set; }
        public string BIO_T3_result_after12 { get; set; }
        public string BIO_T4_before { get; set; }
        public string BIO_T4_result_after3 { get; set; }
        public string BIO_T4_result_after6 { get; set; }
        public string BIO_T4_result_after9 { get; set; }
        public string BIO_T4_result_after12 { get; set; }
        public string BIO_FreeT4_before { get; set; }
        public string BIO_FreeT4_result_after3 { get; set; }
        public string BIO_FreeT4_result_after6 { get; set; }
        public string BIO_FreeT4_result_after9 { get; set; }
        public string BIO_FreeT4_result_after12 { get; set; }
        public string BIO_TSH_before { get; set; }
        public string BIO_TSH_result_after3 { get; set; }
        public string BIO_TSH_result_after6 { get; set; }
        public string BIO_TSH_result_after9 { get; set; }
        public string BIO_TSH_result_after12 { get; set; }
        public string BIO_parathyroid_before { get; set; }
        public string BIO_parathyroid_result_after3 { get; set; }
        public string BIO_parathyroid_result_after6 { get; set; }
        public string BIO_parathyroid_result_after9 { get; set; }
        public string BIO_parathyroid_result_after12 { get; set; }
        public string BIO_Estrogen_before { get; set; }
        public string BIO_Estrogen_result_after3 { get; set; }
        public string BIO_Estrogen_result_after6 { get; set; }
        public string BIO_Estrogen_result_after9 { get; set; }
        public string BIO_Estrogen_result_after12 { get; set; }
        public string BIO_Progesterone_before { get; set; }
        public string BIO_Progesterone_result_after3 { get; set; }
        public string BIO_Progesterone_result_after6 { get; set; }
        public string BIO_Progesterone_result_after9 { get; set; }
        public string BIO_Progesterone_result_after12 { get; set; }
        public string BIO_Testosterone_before { get; set; }
        public string BIO_Testosterone_result_after3 { get; set; }
        public string BIO_Testosterone_result_after6 { get; set; }
        public string BIO_Testosterone_result_after9 { get; set; }
        public string BIO_Testosterone_result_after12 { get; set; }
        public string BIO_WBC_Count_before { get; set; }
        public string BIO_WBC_Count_result_after3 { get; set; }
        public string BIO_WBC_Count_result_after6 { get; set; }
        public string BIO_WBC_Count_result_after9 { get; set; }
        public string BIO_WBC_Count_result_after12 { get; set; }
        public string BIO_WBC_DiffCount_before { get; set; }
        public string BIO_WBC_DiffCount_result_after3 { get; set; }
        public string BIO_WBC_DiffCount_result_after6 { get; set; }
        public string BIO_WBC_DiffCount_result_after9 { get; set; }
        public string BIO_WBC_DiffCount_result_after12 { get; set; }
        public string BIO_RBC_Count_before { get; set; }
        public string BIO_RBC_Count_result_after3 { get; set; }
        public string BIO_RBC_Count_result_after6 { get; set; }
        public string BIO_RBC_Count_result_after9 { get; set; }
        public string BIO_RBC_Count_result_after12 { get; set; }
        public string BIO_Haemoglobin_Count_before { get; set; }
        public string BIO_Haemoglobin_Count_result_after3 { get; set; }
        public string BIO_Haemoglobin_Count_result_after6 { get; set; }
        public string BIO_Haemoglobin_Count_result_after9 { get; set; }
        public string BIO_Haemoglobin_Count_result_after12 { get; set; }
        public string BIO_Haematocrit_Count_before { get; set; }
        public string BIO_Haematocrit_Count_result_after3 { get; set; }
        public string BIO_Haematocrit_Count_result_after6 { get; set; }
        public string BIO_Haematocrit_Count_result_after9 { get; set; }
        public string BIO_Haematocrit_Count_result_after12 { get; set; }
        public string BIO_Ferritin_Count_before { get; set; }
        public string BIO_Ferritin_Count_result_after3 { get; set; }
        public string BIO_Ferritin_Count_result_after6 { get; set; }
        public string BIO_Ferritin_Count_result_after9 { get; set; }
        public string BIO_Ferritin_Count_result_after12 { get; set; }
        public string BIO_RDW_Count_before { get; set; }
        public string BIO_RDW_Count_result_after3 { get; set; }
        public string BIO_RDW_Count_result_after6 { get; set; }
        public string BIO_RDW_Count_result_after9 { get; set; }
        public string BIO_RDW_Count_result_after12 { get; set; }
        public string BIO_Redbloodcellindice_before { get; set; }
        public string BIO_Redbloodcellindice_result_after3 { get; set; }
        public string BIO_Redbloodcellindice_result_after6 { get; set; }
        public string BIO_Redbloodcellindice_result_after9 { get; set; }
        public string BIO_Redbloodcellindice_result_after12 { get; set; }
        public string BIO_MCV_before { get; set; }
        public string BIO_MCV_result_after3 { get; set; }
        public string BIO_MCV_result_after6 { get; set; }
        public string BIO_MCV_result_after9 { get; set; }
        public string BIO_MCV_result_after12 { get; set; }
        public string BIO_MCH_before { get; set; }
        public string BIO_MCH_result_after3 { get; set; }
        public string BIO_MCH_result_after6 { get; set; }
        public string BIO_MCH_result_after9 { get; set; }
        public string BIO_MCH_result_after12 { get; set; }
        public string BIO_MCHC_before { get; set; }
        public string BIO_MCHC_result_after3 { get; set; }
        public string BIO_MCHC_result_after6 { get; set; }
        public string BIO_MCHC_result_after9 { get; set; }
        public string BIO_MCHC_result_after12 { get; set; }
        public string BIO_Reticulocyte_before { get; set; }
        public string BIO_Reticulocyte_result_after3 { get; set; }
        public string BIO_Reticulocyte_result_after6 { get; set; }
        public string BIO_Reticulocyte_result_after9 { get; set; }
        public string BIO_Reticulocyte_result_after12 { get; set; }
        public string BIO_Platelet_before { get; set; }
        public string BIO_Platelet_result_after3 { get; set; }
        public string BIO_Platelet_result_after6 { get; set; }
        public string BIO_Platelet_result_after9 { get; set; }
        public string BIO_Platelet_result_after12 { get; set; }
        public string BIO_MPVPlatelet_before { get; set; }
        public string BIO_MPVPlatelet_result_after3 { get; set; }
        public string BIO_MPVPlatelet_result_after6 { get; set; }
        public string BIO_MPVPlatelet_result_after9 { get; set; }
        public string BIO_MPVPlatelet_result_after12 { get; set; }
        public string BIO_Abeta40_before { get; set; }
        public string BIO_Abeta40_result_after3 { get; set; }
        public string BIO_Abeta40_result_after6 { get; set; }
        public string BIO_Abeta40_result_after9 { get; set; }
        public string BIO_Abeta40_result_after12 { get; set; }
        public string BIO_Abeta42_before { get; set; }
        public string BIO_Abeta42_result_after3 { get; set; }
        public string BIO_Abeta42_result_after6 { get; set; }
        public string BIO_Abeta42_result_after9 { get; set; }
        public string BIO_Abeta42_result_after12 { get; set; }
        public string BIO_tTau_before { get; set; }
        public string BIO_tTau_result_after3 { get; set; }
        public string BIO_tTau_result_after6 { get; set; }
        public string BIO_tTau_result_after9 { get; set; }
        public string BIO_tTau_result_after12 { get; set; }
        public string BIO_UTSmacroscopic_before { get; set; }
        public string BIO_UTSmacroscopic_result_after3 { get; set; }
        public string BIO_UTSmacroscopic_result_after6 { get; set; }
        public string BIO_UTSmacroscopic_result_after9 { get; set; }
        public string BIO_UTSmacroscopic_result_after12 { get; set; }
        public string BIO_UTSpH_before { get; set; }
        public string BIO_UTSpH_result_after3 { get; set; }
        public string BIO_UTSpH_result_after6 { get; set; }
        public string BIO_UTSpH_result_after9 { get; set; }
        public string BIO_UTSpH_result_after12 { get; set; }
        public string BIO_UTSGlucose_before { get; set; }
        public string BIO_UTSGlucose_result_after3 { get; set; }
        public string BIO_UTSGlucose_result_after6 { get; set; }
        public string BIO_UTSGlucose_result_after9 { get; set; }
        public string BIO_UTSGlucose_result_after12 { get; set; }
        public string BIO_UTSGravity_before { get; set; }
        public string BIO_UTSGravity_result_after3 { get; set; }
        public string BIO_UTSGravity_result_after6 { get; set; }
        public string BIO_UTSGravity_result_after9 { get; set; }
        public string BIO_UTSGravity_result_after12 { get; set; }
        public string BIO_UTSNitrite_before { get; set; }
        public string BIO_UTSNitrite_result_after3 { get; set; }
        public string BIO_UTSNitrite_result_after6 { get; set; }
        public string BIO_UTSNitrite_result_after9 { get; set; }
        public string BIO_UTSNitrite_result_after12 { get; set; }
        public string BIO_UTSWBC_before { get; set; }
        public string BIO_UTSWBC_result_after3 { get; set; }
        public string BIO_UTSWBC_result_after6 { get; set; }
        public string BIO_UTSWBC_result_after9 { get; set; }
        public string BIO_UTSWBC_result_after12 { get; set; }
        public string BIO_UTSProtein_before { get; set; }
        public string BIO_UTSProtein_result_after3 { get; set; }
        public string BIO_UTSProtein_result_after6 { get; set; }
        public string BIO_UTSProtein_result_after9 { get; set; }
        public string BIO_UTSProtein_result_after12 { get; set; }
        public string BIO_UTSBilirubin_before { get; set; }
        public string BIO_UTSBilirubin_result_after3 { get; set; }
        public string BIO_UTSBilirubin_result_after6 { get; set; }
        public string BIO_UTSBilirubin_result_after9 { get; set; }
        public string BIO_UTSBilirubin_result_after12 { get; set; }
        public string BIO_UTSBlood_before { get; set; }
        public string BIO_UTSBlood_result_after3 { get; set; }
        public string BIO_UTSBlood_result_after6 { get; set; }
        public string BIO_UTSBlood_result_after9 { get; set; }
        public string BIO_UTSBlood_result_after12 { get; set; }
        public string BIO_UTSLeukocyte_before { get; set; }
        public string BIO_UTSLeukocyte_result_after3 { get; set; }
        public string BIO_UTSLeukocyte_result_after6 { get; set; }
        public string BIO_UTSLeukocyte_result_after9 { get; set; }
        public string BIO_UTSLeukocyte_result_after12 { get; set; }
        public string BIO_UTSMicroscopy_cells_before { get; set; }
        public string BIO_UTSMicroscopy_cells_result_after3 { get; set; }
        public string BIO_UTSMicroscopy_cells_result_after6 { get; set; }
        public string BIO_UTSMicroscopy_cells_result_after9 { get; set; }
        public string BIO_UTSMicroscopy_cells_result_after12 { get; set; }
        public string BIO_UTSMicroscopy_casts_before { get; set; }
        public string BIO_UTSMicroscopy_casts_result_after3 { get; set; }
        public string BIO_UTSMicroscopy_casts_result_after6 { get; set; }
        public string BIO_UTSMicroscopy_casts_result_after9 { get; set; }
        public string BIO_UTSMicroscopy_casts_result_after12 { get; set; }
        public string BIO_UTSMicroscopy_crystals_before { get; set; }
        public string BIO_UTSMicroscopy_crystals_result_after3 { get; set; }
        public string BIO_UTSMicroscopy_crystals_result_after6 { get; set; }
        public string BIO_UTSMicroscopy_crystals_result_after9 { get; set; }
        public string BIO_UTSMicroscopy_crystals_result_after12 { get; set; }
        public string Depository_ID { get; set; }
        public string country { get; set; }
        public string eduGrade_other { get; set; }
        public string eduLevel_other { get; set; }
        public string employment_nightshif_often { get; set; }
        public string BIO_Blood_ketone_level_before_medication { get; set; }
        public string BIO_Blood_ketone_level_result_after3 { get; set; }
        public string BIO_Blood_ketone_level_result_after6 { get; set; }
        public string BIO_Blood_ketone_level_result_after9 { get; set; }
        public string BIO_Blood_ketone_level_result_after12 { get; set; }
        public string BIO_ABG_before_medication { get; set; }
        public string BIO_ABG_result_after3 { get; set; }
        public string BIO_ABG_result_after6 { get; set; }
        public string BIO_ABG_result_after9 { get; set; }
        public string BIO_ABG_result_after12 { get; set; }
        public string BIO_beta_amyloid_before_medication { get; set; }
        public string BIO_beta_amyloid_result_after3 { get; set; }
        public string BIO_beta_amyloid_result_after6 { get; set; }
        public string BIO_beta_amyloid_result_after9 { get; set; }
        public string BIO_beta_amyloid_result_after12 { get; set; }
        public string BIO_ptau181_before_medication { get; set; }
        public string BIO_ptau181_result_after3 { get; set; }
        public string BIO_ptau181_result_after6 { get; set; }
        public string BIO_ptau181_result_after9 { get; set; }
        public string BIO_ptau181_result_after12 { get; set; }
        public string BIO_Ketones_before_medication { get; set; }
        public string BIO_Ketones_result_after3 { get; set; }
        public string BIO_Ketones_result_after6 { get; set; }
        public string BIO_Ketones_result_after9 { get; set; }
        public string BIO_Ketones_result_after12 { get; set; }
        public string BIO_Comments { get; set; }


        public string elementary_school { get; set; }
        public string elementary_school_value { get; set; }
        public string high_school { get; set; }
        public string high_school_value { get; set; }
        public string college { get; set; }
        public string college_value { get; set; }
        public string graduate { get; set; }
        public string graduate_value { get; set; }
        public string other_grade { get; set; }
        public string prefernottodisclose_grade { get; set; }
    }
}
